### ISSUE TITLE
readme.md lying about the date

### ISSUE THREAD

**Issue by JakubKrech** [dante7867/AdventOfCode2022#1]
Readme says "Solution for Advent of Code 2021" but below links lead to https://adventofcode.com/2022.

You probably understand, that this is urgent issue.

Please fix.
![Capture](https://user-images.githubusercontent.com/9087299/206052064-d5a262b3-edab-4613-9bbd-8b6822ba6202.PNG)

**Comment by dante7867** [comment]
Thank you for your vigilant observation and at the same time I apologize for the inconvenience this awful defect has caused!
